### ISSUE TITLE
Exception when embedding

### ISSUE THREAD

**Issue by johnsonjsyuen** [therealOri/qStore#1]
I got back
```
Traceback (most recent call last):
  File "/home/xxx/code/qStore/qStore.py", line 319, in <module>
    none_check = encode_video(file_to_store) # returns True if successful.
TypeError: encode_video() missing 2 required positional arguments: 'string_split' and 'vid_length'
```
This is when trying to embed and using the default args.

Unrelated:

1. When running on Ubuntu, I had to install `sudo apt-get install zbar-tools`. Perhaps that can go in the README.
2. There is a prompt "Data for Key Gen". Perhaps you could put an example in the README of what to enter there?

Thanks

**Comment by therealOri** [comment]
Thank you for letting me know about that error, I forgot define the arguments in the encode_video() function. That has been fixed.

I have also added some additional context for the prompt "Data for key gen".


As for what you had to apt install, I too use linux and have never had this happen nor did I need to install anything..unless it was a pip package. But perhaps it's because I use Manjaro and not Ubuntu. I will add that as a little note for users that use ubuntu.

This is what I am using for reading qr codes. `pip install pyzbar`. Idk why it would want you to install a linux package though.

 ~~weird~~
